### ISSUE TITLE
Sequence contains no matching element

### ISSUE THREAD

**Issue by emilianopenedo** [Fody/Equals#18]
Hi,
I'm getting this exception at compilation with the latest nuget packages (Equals.Fody 1.4.1)
Can be reproduced in a PCL ClassLibrary Project (Profile78) with only a class annotated with [Equals] containing a string auto property
```
Fody: An unhandled exception occurred:
Exception:
Sequence contains no matching element
StackTrace:
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Equals.Fody.ReferenceFinder.FindReferences(IAssemblyResolver assemblyResolver) in c:\Users\vveasel\Desktop\Equals\Fody\ReferenceFinder.cs:line 134
   at ModuleWeaver.Execute() in c:\Users\vveasel\Desktop\Equals\Fody\ModuleWeaver.cs:line 42
   at lambda_method(Closure , Object )
   at InnerWeaver.ExecuteWeavers() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 144
   at InnerWeaver.Execute() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 62
Source:
System.Core
TargetSite:
TSource First[TSource](System.Collections.Generic.IEnumerable`1[TSource], System.Func`2[TSource,System.Boolean])
```

**Comment by emilianopenedo** [comment]
In a PCL ClassLibrary Project (Profile78)
